/*

How many direct and indirect child nodes does each parent node — starting with the element with an id of 1 — have in the DOM generated by the following HTML:

<div id="1">
  <h1 id="2">Hello, <em id="3">World</em></h1>
  <p id="4">
    Welcome to wonderland. This is an
    <span id="5">awesome</span> place.
  </p>
  <a href="#" id="6"><strong id="7">Enter</strong></a>
  <div id="8"><p id="9"><a href="#" id="10">Go back</a></p></div>
</div>

Consider the following when counting the direct and indirect child nodes for each parent node:

* Any DOM node that has at least one child node is a parent node.
* Indirect child nodes are the child nodes of child nodes.

---

id: 1 => 9 elements + 5 empty text = 14
id: 2 => 1 elements
id: 3 => 0 elements
id: 4 => 1 elements
id: 5 => 0 elements
id: 6 => 1 elements
id: 7 => 0 elements
id: 8 => 2 elements
id: 9 => 1 elements
id: 10 => 0 elements

*/
